name: Test Lego Demo Action

on: [push, workflow_dispatch]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Run Lego Demo Action
          uses: papaissad-school/lego-demo-action@main
          with:
            who-to-greet: 'Mona the Octocat'
            github-token: ${{ secrets.GITHUB_TOKEN }}
